name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:

env:
  MISE_AUTO_INSTALL: "false"

jobs:
  stylua-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check lua/

  plenary-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        neovim: ["v0.8.3", "v0.9.5", "v0.10.4"]
        os: ["ubuntu-22.04"]
        include:
          - neovim: "v0.11.6"
            os: "ubuntu-latest"
          - neovim: "stable"
            os: "windows-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: "${{matrix.neovim}}" # use instead of mise b/c treesitter might work better?
      - name: "Install neovim and other deps"
        uses: jdx/mise-action@v2
      - name: "Run tests"
        run: |
          mise use tree-sitter
          mise deps
          mise test

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
