name: EmmyLua Analyzer Diagnostics
on:
  pull_request: ~
  push:
    branches:
      - '*'

env:
  MISE_AUTO_INSTALL_DISABLE_TOOLS: lua-language-server

jobs:
  luals-check:
    strategy:
      matrix:
        neovim: ["nightly"]
        lua: ["luajit-master", "5.1"]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: luarocks/gh-actions-lua@v10
      with:
        luaVersion: ${{matrix.lua}}

    - name: Install tools
      uses: jdx/mise-action@v2
      with:
        install_args: "github:neovim/neovim@nightly"

    - name: Run emmylua_check
      continue-on-error: true
      run: |
        mise use github:neovim/neovim@nightly
        mise run deps
        NEOTREE_LUARC=".github/workflows/.luarc-${{ matrix.lua }}.json" mise run emmylua-check
