name: Lua Language Server Diagnostics
on:
  pull_request: ~
  push:
    branches:
      - '*'

env:
  MISE_AUTO_INSTALL_DISABLE_TOOLS: cargo-binstall,cargo:emmylua_ls,cargo:emmylua_check

jobs:
  luals-check:
    strategy:
      matrix:
        include:
          - neovim: "0.11"
            lua: "5.1"
          - neovim: "nightly"
            lua: "luajit-master"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: luarocks/gh-actions-lua@v10
      with:
        luaVersion: ${{matrix.lua}}

    - name: Install tools
      uses: jdx/mise-action@v2
      with:
        install_args: "github:neovim/neovim@${{matrix.neovim}}"

    - name: Run lua-language-server check
      run: |
        mise use github:neovim/neovim@${{matrix.neovim}}
        NEOTREE_LUARC=".github/workflows/.luarc-${{ matrix.lua }}.json" mise run luals-check
