# This is a basic workflow to help you get started with Actions

name: No PRs to Release Branches

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the v1.x branch
  pull_request:
    branches:
      - 'v1.x'
      - 'v2.x'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Fail every time
        run: exit 1
